# Form implementation generated from reading ui file 'ui/SplashScreen.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 563)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(853, 563))
        self.centralwidget.setMaximumSize(QtCore.QSize(853, 563))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Splashframe = QtWidgets.QFrame(parent=self.centralwidget)
        self.Splashframe.setMinimumSize(QtCore.QSize(853, 563))
        self.Splashframe.setMaximumSize(QtCore.QSize(853, 563))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        self.Splashframe.setFont(font)
        self.Splashframe.setStyleSheet("#Splashframe{\n"
"\n"
" border-image: url(\"C:/Users/gabby/Documents/Designer_UIS/LearningProgressBar/SplashsScreen/images/teslastyleimage.jpeg\");\n"
"\n"
"}\n"
"")
        self.Splashframe.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Splashframe.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Splashframe.setObjectName("Splashframe")
        self.label = QtWidgets.QLabel(parent=self.Splashframe)
        self.label.setGeometry(QtCore.QRect(10, 0, 791, 41))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(254,121,199);\n"
"background:transparent;")
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(parent=self.Splashframe)
        self.progressBar.setGeometry(QtCore.QRect(110, 510, 731, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* Subtle glass border */\n"
"    border-radius: 10px;\n"
"    background-color: rgba(40, 20, 60, 150); /* Dark Deep Purple Track */\n"
"    text-align: center;\n"
"    color: white; /* Progress percentage color */\n"
"    font-weight: bold;\n"
"    height: 20px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    /* The \"Moving\" part - Neon Magenta to Amethyst Gradient */\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, \n"
"        stop:0 #ff00ff, \n"
"        stop:1 #8a2be2); \n"
"    border-radius: 8px; /* Slightly smaller than the main bar for a clean look */\n"
"    margin: 2px; /* Adds a tiny gap between the bar and the border */\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.loaderLabel = QtWidgets.QLabel(parent=self.Splashframe)
        self.loaderLabel.setGeometry(QtCore.QRect(320, 530, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        self.loaderLabel.setFont(font)
        self.loaderLabel.setStyleSheet("color:rgb(254,121,199);\n"
"background:transparent;")
        self.loaderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loaderLabel.setObjectName("loaderLabel")
        self.label_3 = QtWidgets.QLabel(parent=self.Splashframe)
        self.label_3.setGeometry(QtCore.QRect(0, 540, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe Fluent Icons")
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: whitesmoke;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.Splashframe, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<strong>SMART</strong> NAVIGATION SYSTEM"))
        self.loaderLabel.setText(_translate("MainWindow", "Loading......"))
        self.label_3.setText(_translate("MainWindow", "©DevKau"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
